INSERT INTO Physician2 VALUES ('D01', 'Anthony Mackie', 'Dermatology');
INSERT INTO Physician2 VALUES ('D02', 'Margot Robbie', 'Anesthesiology');
INSERT INTO Physician2 VALUES ('D03', 'Ryan Gosling', 'Family Medicine');
INSERT INTO Physician2 VALUES ('D04', 'Dwayne Johnson', 'Surgery');
INSERT INTO Physician2 VALUES ('D05', 'Emma Stone', 'Internal Medicine');
INSERT INTO Physician2 VALUES ('D06', 'Tom Hanks', 'Dermatology');
INSERT INTO Physician2 VALUES ('D07', 'Idris Elba', 'Anesthesiology');
INSERT INTO Physician2 VALUES ('D08', 'Gal Gadot', 'Family Medicine');
INSERT INTO Physician2 VALUES ('D09', 'Will Ferrell', 'Internal Medicine');
INSERT INTO Physician2 VALUES ('D10', 'Chris Evans', 'Dermatology');
INSERT INTO Physician2 VALUES ('D11', 'Jamie Foxx', 'Surgery');
INSERT INTO Physician2 VALUES ('D12', 'Tom Hardy', 'Anesthesiology');
INSERT INTO Physician2 VALUES ('D13', 'Rami Malek', 'Psychiatry');
INSERT INTO Physician2 VALUES ('D14', 'Vin Diesel', 'Psychiatry');
INSERT INTO Physician2 VALUES ('D15', 'Adam Driver', 'Cardiology');
INSERT INTO Physician2 VALUES ('D16', 'Scarlett Johansson', 'Family Medicine');
INSERT INTO Physician2 VALUES ('D17', 'Miles Teller', 'Cardiology');
INSERT INTO Physician2 VALUES ('D18', 'Salma Hayek', 'Psychiatry');
INSERT INTO Physician2 VALUES ('D19', 'Russell Crowe', 'Family Medicine');
INSERT INTO Physician2 VALUES ('D20', 'Ewan McGregor', 'Surgery');
INSERT INTO Physician2 VALUES ('D21', 'Ryan Reynolds', 'Family Medicine');
INSERT INTO Physician2 VALUES ('D22', 'Tom Cruise', 'Dermatology');
INSERT INTO Physician2 VALUES ('D23', 'Natalie Portman', 'Family Medicine');
commit;